name: My first workflow

on: 
  push
  
jobs: 
  first-job:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: List the content of README.md
      run: 
        cat README.md

    - name: Print the echo
      run: echo "My first github actions job"

    - name: Generate ASCII artwork
      run: cowsay -f dragon "Run to save your life, I am a Dragon....RAWR" >> dragon.txt